# Generated by Django 4.2.7 on 2024-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
    ]
